version: "3"

services:
  docs:
    build: docs
    command: poetry run sphinx-autobuild --host 0.0.0.0 /app /app/_build
    volumes:
      - "${PWD}/docs:/app/"
    ports:
      - "35730:35730"
      - "8000:8000"